### ISSUE TITLE
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

### ISSUE THREAD

**Issue by tkafka** [Webreaper/Damselfly#357]
Hello, I can see this in a console of a `webreaper/damselfly:dev` (the latest version from yesterday), Damselfly stops responding to requests.

This happened after trying to create admin user (I've been running without any users before). Creating of the user was very slow, is it possible that the app was interrupted somehow? Or this might be just a coincidence.

```
[19:05:28.010-0001-INF] Startup complete. Reducing console logging level to [Warning/Error].
[19:06:00.169-Kestrel Timer-WRN] As of "06/08/2022 19:05:51 +00:00", the heartbeat has been running for "00:00:02.0414698" which is longer than "00:00:01". This could be caused by thread pool starvation.
[19:07:16.267-Kestrel Timer-WRN] As of "06/08/2022 19:06:43 +00:00", the heartbeat has been running for "00:00:06.3181621" which is longer than "00:00:01". This could be caused by thread pool starvation.
[19:07:55.775-.NET ThreadPool Worker-WRN] Database locked for SaveHash - sleeping for 5s and retying 3...
[19:08:47.756-Kestrel Timer-WRN] As of "06/08/2022 19:08:13 +00:00", the heartbeat has been running for "00:00:17.3225075" which is longer than "00:00:01". This could be caused by thread pool starvation.
[19:10:31.100-Kestrel Timer-WRN] As of "06/08/2022 19:08:57 +00:00", the heartbeat has been running for "00:01:34.0046975" which is longer than "00:00:01". This could be caused by thread pool starvation.
[19:11:23.074-Kestrel Timer-WRN] As of "06/08/2022 19:11:04 +00:00", the heartbeat has been running for "00:00:10.1676307" which is longer than "00:00:01". This could be caused by thread pool starvation.
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.Remove(T item)
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.PruneCallback(Object _)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by Webreaper** [comment]
Looks like the app got into a bad state - perhaps the CPU was overloaded from processing etc, and everything ground to a halt. Did restarting the container fix it?
