### ISSUE TITLE
Dev version: JsonException when trying to load any tag

### ISSUE THREAD

**Issue by YorVeX** [Webreaper/Damselfly#449]
When I click at the "Tag Management" button at the top the list with tags Damselfly found comes up just fine, I can also jump through the pages. But as soon as I click any of the tags (no matter which one) I get the message "An error occurred. Please check the Damselfly logs and reload the page."

The log then shows a JsonException:
```
2022-11-25 00:21:37 [23:21:40.689-.NET ThreadPool Worker-ERR] System.Text.Json.JsonException: ExpectedStartOfValueNotFound, < Path: $ | LineNumber: 0 | BytePositionInLine: 0.
2022-11-25 00:21:37  ---> System.Text.Json.JsonReaderException: ExpectedStartOfValueNotFound, < LineNumber: 0 | BytePositionInLine: 0.
2022-11-25 00:21:37    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& , ExceptionResource , Byte , ReadOnlySpan`1 )
2022-11-25 00:21:37    at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte )
2022-11-25 00:21:37    at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte )
2022-11-25 00:21:37    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
2022-11-25 00:21:37    at System.Text.Json.Utf8JsonReader.Read()
2022-11-25 00:21:37    at System.Text.Json.Serialization.JsonConverter`1[[Damselfly.Core.Models.Tag, Damselfly.Core.DbModels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
2022-11-25 00:21:37    Exception_EndOfInnerExceptionStack
2022-11-25 00:21:37    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException )
2022-11-25 00:21:37    at System.Text.Json.Serialization.JsonConverter`1[[Damselfly.Core.Models.Tag, Damselfly.Core.DbModels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
2022-11-25 00:21:37    at System.Text.Json.JsonSerializer.ReadCore[Tag](Utf8JsonReader& , JsonTypeInfo , ReadStack& )
2022-11-25 00:21:37    at System.Text.Json.JsonSerializer.ContinueDeserialize[Tag](ReadBufferState& , JsonReaderState& , ReadStack& , JsonTypeInfo )
2022-11-25 00:21:37    at System.Text.Json.JsonSerializer.<ReadFromStreamAsync>d__76`1[[Damselfly.Core.Models.Tag, Damselfly.Core.DbModels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
2022-11-25 00:21:37    at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__5`1[[Damselfly.Core.Models.Tag, Damselfly.Core.DbModels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
2022-11-25 00:21:37    at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__29`1[[Damselfly.Core.Models.Tag, Damselfly.Core.DbModels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
2022-11-25 00:21:37    at Damselfly.Core.ScopedServices.ClientServices.RestClient.<CustomGetFromJsonAsync>d__8`1[[Damselfly.Core.Models.Tag, Damselfly.Core.DbModels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
2022-11-25 00:21:37    at Damselfly.Core.ScopedServices.ClientTagService.GetTag(Int32 tagId)
2022-11-25 00:21:37    at Damselfly.Web.Client.Pages.HomePage.ApplyQueryParams()
2022-11-25 00:21:37    at Damselfly.Web.Client.Pages.HomePage.OnInitializedAsync()
2022-11-25 00:21:37    at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
2022-11-25 00:21:37    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
2022-11-25 00:21:37 System.Text.Json.JsonException: ExpectedStartOfValueNotFound, < Path: $ | LineNumber: 0 | BytePositionInLine: 0.
2022-11-25 00:21:37  ---> System.Text.Json.JsonReaderException: ExpectedStartOfValueNotFound, < LineNumber: 0 | BytePositionInLine: 0.
2022-11-25 00:21:37    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& , ExceptionResource , Byte , ReadOnlySpan`1 )
2022-11-25 00:21:37    at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte )
2022-11-25 00:21:37    at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte )
2022-11-25 00:21:37    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
2022-11-25 00:21:37    at System.Text.Json.Utf8JsonReader.Read()
2022-11-25 00:21:37    at System.Text.Json.Serialization.JsonConverter`1[[Damselfly.Core.Models.Tag, Damselfly.Core.DbModels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
2022-11-25 00:21:37    Exception_EndOfInnerExceptionStack
2022-11-25 00:21:37    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException )
2022-11-25 00:21:37    at System.Text.Json.Serialization.JsonConverter`1[[Damselfly.Core.Models.Tag, Damselfly.Core.DbModels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
2022-11-25 00:21:37    at System.Text.Json.JsonSerializer.ReadCore[Tag](Utf8JsonReader& , JsonTypeInfo , ReadStack& )
2022-11-25 00:21:37    at System.Text.Json.JsonSerializer.ContinueDeserialize[Tag](ReadBufferState& , JsonReaderState& , ReadStack& , JsonTypeInfo )
2022-11-25 00:21:37    at System.Text.Json.JsonSerializer.<ReadFromStreamAsync>d__76`1[[Damselfly.Core.Models.Tag, Damselfly.Core.DbModels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
2022-11-25 00:21:37    at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__5`1[[Damselfly.Core.Models.Tag, Damselfly.Core.DbModels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
2022-11-25 00:21:37    at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__29`1[[Damselfly.Core.Models.Tag, Damselfly.Core.DbModels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
2022-11-25 00:21:37    at Damselfly.Core.ScopedServices.ClientServices.RestClient.<CustomGetFromJsonAsync>d__8`1[[Damselfly.Core.Models.Tag, Damselfly.Core.DbModels, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
2022-11-25 00:21:37    at Damselfly.Core.ScopedServices.ClientTagService.GetTag(Int32 tagId)
2022-11-25 00:21:37    at Damselfly.Web.Client.Pages.HomePage.ApplyQueryParams()
2022-11-25 00:21:37    at Damselfly.Web.Client.Pages.HomePage.OnInitializedAsync()
2022-11-25 00:21:37    at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
2022-11-25 00:21:37    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

**Comment by Webreaper** [comment]
Thanks for the bug report! Fixed! :)

**Comment by YorVeX** [comment]
Yes, it's working now, thanks!
