### ISSUE TITLE
An unhandled exception was thrown by the application

### ISSUE THREAD

**Issue by whoopn** [Webreaper/Damselfly#455]
I'm getting this error when I first access the GUI:

![image](https://user-images.githubusercontent.com/2213683/205461598-ebd7707b-2699-4b4d-ba98-3b60a56d57e4.png)

Logs show only this one error during this time (logging is on default):
<html>
<body>

14:11:18.675 | ERR | Connection id "0HMMKO31IDFA0", Request id "0HMMKO31IDFA0:0000007F": An unhandled exception was thrown by the application
-- | -- | --

</body>
</html>

Have you encountered this before?

**Comment by Webreaper** [comment]
Haven't seen that. Can you send me the full log file?

If you refresh the page, does it sort itself out?

**Comment by whoopn** [comment]
Additional information:
The folder sidebar doesn't load either. Just stays at loading.


[Damselfly-20221203.log](https://github.com/Webreaper/Damselfly/files/10147408/Damselfly-20221203.log)

**Comment by whoopn** [comment]
Ok more information if it helps:

When I just went to add a user through the desktop app I received this error:

System.NullReferenceException: Arg_NullReferenceException
   at Damselfly.Web.Client.Shared.UserManagement.OpenUserDialog(AppIdentityUser user)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

**Comment by whoopn** [comment]
I'm using Unraid 6.11.5 for the server side, its actively scanning.

Also, I just noticed the db is sitting on a spinning drive, I'm going to move that over to the cache drive.

**Comment by Webreaper** [comment]
The first exception is this, I know the cause of this. I'll look at a fix
in the next couple of days when I get time.

`An unhandled exception was thrown by the application.
System.Text.Json.JsonException: A possible object cycle was detected.
This can either be due to a cycle or if the object depth is larger
than the maximum allowed depth of 32. Consider using
ReferenceHandler.Preserve on JsonSerializerOptions to support cycles.
Path: $.Children.Children.Children.Children.Children.Children.Children.Children.Children.Subfolders.
   at System.Text.Json.ThrowHelper.`

**Comment by whoopn** [comment]
> Can you try pulling `webreaper/damselfly:dev` and tell me if it solves the issue?

It would appear it did fix the bottom of the screen error but now I am seeing this (only once and reloading did help):
"System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode, 500, Internal Server Error
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__29`1[[Damselfly.Core.Models.Basket, Damselfly.Core.DbModels, Version=4.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Damselfly.Core.ScopedServices.ClientServices.RestClient.<CustomGetFromJsonAsync>d__8`1[[Damselfly.Core.Models.Basket, Damselfly.Core.DbModels, Version=4.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Damselfly.Core.ScopedServices.ClientBasketService.SwitchToDefaultBasket(Nullable`1 userId)
   at Damselfly.Web.Client.Shared.BasketManager.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )"

I have to say the folder view working is really nifty! When do you think this commit will be released?

**Comment by Webreaper** [comment]
I'll have a look at the exception above, but will put out a small patch with the change now that fixed you, so you can switch to the non-develop image. :)
