### ISSUE TITLE
Exception in ContextMenu code: Cannot read property 'dataset' of null

### ISSUE THREAD

**Issue by Webreaper** [Webreaper/Damselfly#46]
[11:10:59.718-3323-WRN] Unhandled exception rendering component: Cannot read property 'dataset' of null
TypeError: Cannot read property 'dataset' of null
    at Object.f.RegisterTriggerReference (http://192.168.1.120:6363/_content/Blazor.ContextMenu/blazorContextMenu.min.js:1:3579)
    at http://192.168.1.120:6363/_framework/blazor.server.js:1:70053
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://192.168.1.120:6363/_framework/blazor.server.js:1:70019)
    at http://192.168.1.120:6363/_framework/blazor.server.js:1:26303
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://192.168.1.120:6363/_framework/blazor.server.js:1:26273)
    at e.processIncomingData (http://192.168.1.120:6363/_framework/blazor.server.js:1:24211)
    at e.connection.onreceive (http://192.168.1.120:6363/_framework/blazor.server.js:1:17296)
    at WebSocket.i.onmessage (http://192.168.1.120:6363/_framework/blazor.server.js:1:46513)

**Comment by Webreaper** [comment]
Replaced context menus with the Radzen ones, for now.
