### ISSUE TITLE
No photos at all showing - Basket: An error has occurred.   

### ISSUE THREAD

**Issue by turkeyphant** [Webreaper/Damselfly#508]
```
System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode, 500, Internal Server Error
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__29`1[[Damselfly.Core.Models.Basket, Damselfly.Core.DbModels, Version=4.0.8.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Damselfly.Core.ScopedServices.ClientServices.RestClient.<CustomGetFromJsonAsync>d__8`1[[Damselfly.Core.Models.Basket, Damselfly.Core.DbModels, Version=4.0.8.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Damselfly.Core.ScopedServices.ClientBasketService.SwitchToDefaultBasket(Nullable`1 userId)
   at Damselfly.Web.Client.Shared.BasketManager.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```
is the error I get

**Comment by turkeyphant** [comment]
All folders is also showing empty even though mapped correctly in docker

**Comment by turkeyphant** [comment]
Is it not following softlinks or something?!

**Comment by Webreaper** [comment]
May not support softlinks, no. Try mounting the individual folders as child folders of the /pictures folder in the docker contsiner.
