### ISSUE TITLE
Error starting container

### ISSUE THREAD

**Issue by daleao** [Webreaper/Damselfly#545]
Errors are thrown when attempting to start the container.

Compose file:
```
services:
    damselfly:
        container_name: damselfly
        image: webreaper/damselfly
        ports:
            - 6363:6363/tcp
        volumes:
            - ./config:/config
            - ./thumbs:/thumbs
            - /share/Vault/Animated/Raw:/pictures
        restart: unless-stopped
```

Docker logs:
```
Preparing to start Damselfly....
  ./Damselfly.Web.Server /pictures --config=/config --thumbs=/thumbs
Creating log folder /config/logs
[02:45:04.583-0001-INF] === Damselfly Blazor Server Log Started ===
[02:45:04.873-0001-INF] Running Sqlite DB migrations...
[02:45:06.764-0001-WRN] Migrations failed with exception: System.InvalidOperationException: An error was generated for warning 'Microsoft.EntityFrameworkCore.Migrations.PendingModelChangesWarning': The model for context 'ImageContext' has pending changes. Add a new migration before updating the database. This exception can be suppressed or logged by passing event ID 'RelationalEventId.PendingModelChangesWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, TParam arg)
   at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.PendingModelChangesWarning(IDiagnosticsLogger`1 diagnostics, Type contextType)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Damselfly.Web.Program.InitialiseDB(WebApplication app, DamselflyOptions options)
[02:45:06.764-0001-INF] Creating DB.
[02:45:07.678-0001-INF] Running Sqlite DB optimisation...
[02:45:07.685-0001-INF] DB optimisation complete.
[02:45:07.718-0001-ERR] Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
DELETE from FTSKeywords; DELETE from FTSImages; DELETE from FTSNames; INSERT INTO FTSKeywords (TagId, Keyword) SELECT t.TagId, t.Keyword FROM Tags t; INSERT INTO FTSNames (PersonID, Name) SELECT PersonId, Name FROM people p where p.State = 1; INSERT INTO FTSImages ( ImageId, Caption, Description, Copyright, Credit )
                                SELECT i.ImageId, i.Caption, i.Description, i.CopyRight, i.Credit FROM imagemetadata i
                                WHERE (coalesce(i.Caption, '') <> '' OR coalesce(i.Description, '') <> ''
                                     OR coalesce(i.Copyright, '') <> '' OR coalesce(i.Credit, '') <> '');
Startup exception: System.AggregateException: One or more errors occurred. (SQLite Error 1: 'no such table: FTSKeywords'.)
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: FTSKeywords'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlRawAsync(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
   at Damselfly.Core.DBAbstractions.BaseDBModel.RebuildFreeText()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Damselfly.Core.DBAbstractions.BaseDBModel.IncreasePerformance()
   at Damselfly.Web.Program.InitialiseDB(WebApplication app, DamselflyOptions options)
   at Damselfly.Web.Program.StartWebServer(DamselflyOptions cmdLineOptions, String[] args)
   at Damselfly.Web.Program.Startup(DamselflyOptions o, String[] args)
   at Damselfly.Web.Program.<>c__DisplayClass0_0.<Main>b__0(DamselflyOptions o)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Damselfly.Web.Program.Main(String[] args)
Preparing to start Damselfly....
  ./Damselfly.Web.Server /pictures --config=/config --thumbs=/thumbs
```

**Comment by Webreaper** [comment]
Thanks for reporting. Will have a fix ready shortly.

**Comment by Webreaper** [comment]
Fix here: https://github.com/Webreaper/Damselfly/releases/tag/4.2.1 - please give it a try
